"""fix added status to checked

Revision ID: 320d67eec380
Revises: bedf1d2c7ed0
Create Date: 2025-07-31 09:38:09.238808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '320d67eec380'
down_revision: Union[str, Sequence[str], None] = 'bedf1d2c7ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checked_audio', sa.Column('status', postgresql.ENUM('pending', 'approved', name='audiostatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checked_audio', 'status')
    # ### end Alembic commands ###
