"""fix sentence confilic

Revision ID: 34f408308de4
Revises: 2290887152bc
Create Date: 2025-07-30 18:08:29.922681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '34f408308de4'
down_revision: Union[str, Sequence[str], None] = '2290887152bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE TYPE audiostatus AS ENUM ('pending', 'approved')"))
    op.add_column('received_audio', sa.Column('status', sa.Enum('pending', 'approved', name='audiostatus'), nullable=True))
    op.alter_column('received_audio', 'audio_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('received_audio', 'audio_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('received_audio', 'status')
    # ### end Alembic commands ###
