"""fix: checked_audio

Revision ID: 537d33e7f6fa
Revises: 6d31a085e8f6
Create Date: 2025-07-29 17:52:38.110698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537d33e7f6fa'
down_revision: Union[str, Sequence[str], None] = '6d31a085e8f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checked_audio', 'checked_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checked_audio', 'checked_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
