"""is correct

Revision ID: c1881804904f
Revises: 0c1382d7c2b5
Create Date: 2025-07-31 18:36:32.226948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1881804904f'
down_revision: Union[str, Sequence[str], None] = '0c1382d7c2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checked_audio', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checked_audio', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
