"""remove unused 'used_count' in sentence

Revision ID: f3bfba4978e0
Revises: c1881804904f
Create Date: 2025-08-11 16:36:22.093740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bfba4978e0'
down_revision: Union[str, Sequence[str], None] = 'c1881804904f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentences', 'used_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('used_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
